# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
    ContainerRegistry: "ghcr.io"
    ContainerRegistryRepo: "ghcr.io/eclipse-symphony"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Set up custom GOPATH
      run: |
        mkdir -p /home/runner/go
        echo "export GOPATH=/home/runner/go" >> $HOME/.bashrc
        echo "export PATH=\$PATH:\$GOPATH/bin" >> $HOME/.bashrc
        source $HOME/.bashrc

    - name: Install make
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Check docker version and images
      run: docker --version && docker images

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        kubectl version --client
        kubectl config view

    - name: Install minikube
      run: | 
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        minikube start
        kubectl config view
    
    - name: Install Mage
      run: |
        cd ..
        git clone https://github.com/magefile/mage
        cd mage
        go run bootstrap.go
        cd ..

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.ContainerRegistry }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build docker images
      run: |
        cd test/localenv/ && mage build:all

    - name: Run integration tests
      run: |
        export REPO_PATH="${{ github.workspace }}"
        echo "REPO_PATH=$REPO_PATH"
        cd test/integration/ && mage test